const features = [
  'telewizja kablowa',
  'domofon / wideofon',
  'balkon',
  'piwnica',
  'winda',
  'internet',
  'rolety antywłamaniowe',
  'ogródek',
  'pom. użytkowe',
  'telefon',
  'garaż/miejsce parkingowe',
  'oddzielna kuchnia',
  'drzwi / okna antywłamaniowe',
  'lodówka',
  'meble',
  'kuchenka',
  'pralka',
  'monitoring / ochrona',
  'zmywarka',
  'piekarnik',
  'taras',
  'teren zamknięty',
  'telewizor',
  'system alarmowy',
  'klimatyzacja',
  'dwupoziomowe',
]

export default features
