const locations = [
  { id: '79', label: 'Grunwald' },
  { id: '98', label: 'Rataje' },
  { id: '109', label: 'Winogrady' },
  { id: '80', label: 'Jeżyce' },
  { id: '90', label: 'Naramowice' },
  { id: '', label: '', type: '' },
  { id: '91', label: 'Nowe Miasto' },
  { id: '87', label: 'Łazarz' },
  { id: '78', label: 'Górczyn' },
  { id: '107', label: 'Wilda' },
  { id: '103', label: 'Stare Miasto' },
  { id: '146768', label: 'Centrum' },
  { id: '88', label: 'Malta' },
  { id: '93', label: 'Piątkowo' },
  { id: '102', label: 'Śródka' },
  { id: '94', label: 'Podolany' },
  { id: '108', label: 'Winiary' },
  { id: '104', label: 'Starołęka' },
  { id: '86', label: 'Ławica' },
  { id: '14704', label: 'Główna' },
  { id: '105', label: 'Strzeszyn' },
  { id: '74', label: 'Dębiec' },
  { id: '3610', label: 'Wilczak' },
  { id: '73', label: 'Chartowo' },
  { id: '100', label: 'Sołacz' },
  { id: '9984', label: 'Zawady' },
  { id: '14747', label: 'Ostrów Tumski' },
  { id: '3576', label: 'Kobyle Pole' },
  { id: '81', label: 'Junikowo' },
  { id: '62283', label: 'Górna Wilda' },
  { id: '69419', label: 'Smochowice' },
  { id: '70878', label: 'Trójpole' },
  { id: '18856', label: 'Żegrze' },
  { id: '5221', label: 'Dolna Wilda' },
  { id: '13195', label: 'Garbary' },
  { id: '11415', label: 'Stary Rynek' },
  { id: '2612', label: 'Antoninek' },
  { id: '92', label: 'Ogrody' },
  { id: '106', label: 'Świerczewo' },
  { id: '2495', label: 'Szczepankowo' },
  { id: '13553', label: 'Warszawskie' },
  { id: '89', label: 'Marcelin' },
  { id: '793', label: 'Bonin' },
  { id: '46693', label: 'Chwaliszewo' },
  { id: '5373', label: 'Zieliniec' },
  { id: '6558', label: 'Morasko' },
  { id: '5391', label: 'Wilczy Młyn' },
  { id: '84', label: 'Kotowo' },
  { id: '97', label: 'Raszyn' },
  { id: '56985', label: 'Naramowickie Osiedle' },
  { id: '26695', label: 'Darzybór' },
  { id: '42373', label: 'Rynek Łazarski' },
  { id: '75', label: 'Fabianowo' },
  { id: '14827', label: 'Rynek Jeżycki' },
  { id: '77', label: 'Głuszyna' },
  { id: '300522', label: 'Bajkowe' },
  { id: '2399', label: 'Wola' },
  { id: '11744', label: 'Radojewo' },
  { id: '51219', label: 'Nadolnik' },
  { id: '76', label: 'Franowo' },
  { id: '54068', label: 'Rynek Wildecki' },
  { id: '11445', label: 'Krzyżowniki' },
  { id: '877', label: 'Umultowo' },
  { id: '85', label: 'Krzesiny' },
  { id: '60063', label: 'Święty Roch' },
]

export default locations
